### ISSUE TITLE
CFLite does not compile

### ISSUE THREAD

**Issue by spotlightishere** [fjolnir/CoreFoundation-Lite-Linux#1]
Since the Apple supplied version does not compile correctly for me, I went to this fork. It works farther than any other clone I have used :+1: 

However, it does error out. I am using the stock supplied clang/libBlocksRuntime/ICJ4C/etc. I am on Ubuntu 14.04 LTS.

```
/usr/bin/clang -O0 -g -c -x c -fblocks -fpic -pipe -std=gnu99 -Wno-trigraphs -fexceptions -DCF_BUILDING_CF=1 -DDEPLOYMENT_TARGET_LINUX=1 -DMAC_OS_X_VERSION_MAX_ALLOWED=MAC_OS_X_VERSION_10_7 -DU_SHOW_DRAFT_API=1 -DU_SHOW_CPLUSPLUS_API=0 -ICF-Objects/normal -ICF-Objects/normal/CoreFoundation -DVERSION=744.12 -include CoreFoundation_Prefix.h     CFTimeZone.c -o CF-Objects/normal/CFTimeZone.o
CFTimeZone.c:84:75: error: alias must point to a defined variable or function
CF_EXPORT CFStringRef const kCFDateFormatterTimeZone __attribute__((weak, alias   ("kCFDateFormatterTimeZoneKey")));
                                                                      ^
1 error generated.
```

Thank you in advance, and I hope this is still supported!

**Comment by fjolnir** [comment]
It looks like you can just comment out the offending line, the alias is also set up in CFLocaleKeys.c

 I'm not updating this repo until Yosemite's CFLite gets released (open source.apple.com says "coming soon", but has said that for a while)

**Comment by spotlightishere** [comment]
I can't access my Ubuntu box right now, but I can access a Debian box. I cant't even get to this error, it fails, I'll report another issue.

**Comment by fjolnir** [comment]
please do

**Comment by drudru** [comment]
BTW - got the same error. Commented it out. It compiled. Thx.

**Comment by spotlightishere** [comment]
Unfortunately I never got around to trying it out, sorry. If commenting it out worked for both of you it probably would have worked for me.
