### ISSUE TITLE
CFArray errors out

### ISSUE THREAD

**Issue by spotlightishere** [fjolnir/CoreFoundation-Lite-Linux#2]
On a Debian box running clang 3.0, CFArray.c errors out with the following error:
`CFArray.c:866:9: error: use of undeclared identifier 'HALT'`

I am not sure how to fix this.

**Comment by fjolnir** [comment]
HALT is defined in CFInternal.h try adding #include "CFInternal.h" to the top of CFArray.c and let me know if that fixes it.

No idea why this would only happen on your specific setup though.

**Comment by spotlightishere** [comment]
That is already included. CFLite seems to be extremely platform depedent. This is weird.

**Comment by spotlightishere** [comment]
I found out why.

HALT is only defined if you have an i386 or x86 machine. I don't, I have a PowerPC. So I need to find an alternative ASM instructuon.

**Comment by fjolnir** [comment]
Ah,
I don't think CFLite is supported at all on Linux/PPC

**Comment by spotlightishere** [comment]
No, I found that out just now. A quick patch is to replicate the ASM with trap. I gave up and went with OpenCFLite, which works pretty well. Thank you!
